// <auto-generated />
using System;
using DAL.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506184956_AddConstraintsAndIndexes")]
    partial class AddConstraintsAndIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockIndex")
                        .HasColumnType("int");

                    b.Property<string>("BlockNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Blocks__3214EC078A32433B");

                    b.HasIndex(new[] { "BlockNumber" }, "UQ__Blocks__14FE551247B77DCB")
                        .IsUnique();

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("DAL.Entities.BlockWeeklyScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("InspectionDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__BlockWee__3214EC07B2D78352");

                    b.HasIndex(new[] { "BlockId" }, "IX_BlockWeeklyScores_BlockId");

                    b.HasIndex(new[] { "Year", "WeekNumber" }, "IX_BlockWeeklyScores_WeekYear");

                    b.HasIndex(new[] { "BlockId", "WeekNumber", "Year" }, "UQ__BlockWee__B4EF87A4ADA6B02B")
                        .IsUnique();

                    b.ToTable("BlockWeeklyScores");
                });

            modelBuilder.Entity("DAL.Entities.DormitoryWeeklyStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime?>("CalculatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("TotalBlocks")
                        .HasColumnType("int");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Dormitor__3214EC07783661FD");

                    b.HasIndex(new[] { "Year", "WeekNumber" }, "IX_DormitoryWeeklyStats_WeekYear");

                    b.HasIndex(new[] { "WeekNumber", "Year" }, "UQ__Dormitor__0AD9254AA84205AC")
                        .IsUnique();

                    b.ToTable("DormitoryWeeklyStats");
                });

            modelBuilder.Entity("DAL.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<int?>("PointsAwarded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Events__3214EC0775634156");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("DAL.Entities.EventParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ParticipatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__EventPar__3214EC077C818A4F");

                    b.HasIndex(new[] { "EventId" }, "IX_EventParticipants_EventId");

                    b.HasIndex(new[] { "UserId" }, "IX_EventParticipants_UserId");

                    b.HasIndex(new[] { "EventId", "UserId" }, "UQ__EventPar__A83C44D5EC688677")
                        .IsUnique();

                    b.ToTable("EventParticipants");
                });

            modelBuilder.Entity("DAL.Entities.FloorWeeklyStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("BlocksCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CalculatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__FloorWee__3214EC074E922ABA");

                    b.HasIndex(new[] { "Year", "WeekNumber" }, "IX_FloorWeeklyStats_WeekYear");

                    b.HasIndex(new[] { "Floor", "WeekNumber", "Year" }, "UQ__FloorWee__4F348CC2F4168D60")
                        .IsUnique();

                    b.ToTable("FloorWeeklyStats");
                });

            modelBuilder.Entity("DAL.Entities.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("InspectionDate")
                        .HasColumnType("date");

                    b.Property<int>("InspectorId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Inspecti__3214EC07365A8B48");

                    b.HasIndex("RoomId");

                    b.HasIndex("ZoneId");

                    b.HasIndex(new[] { "BlockId" }, "IX_Inspections_BlockId");

                    b.HasIndex(new[] { "InspectionDate" }, "IX_Inspections_InspectionDate");

                    b.HasIndex(new[] { "InspectorId" }, "IX_Inspections_InspectorId");

                    b.ToTable("Inspections", t =>
                        {
                            t.HasCheckConstraint("CK_Inspections_Score", "[Score] >= 0 AND [Score] <= 10");
                        });
                });

            modelBuilder.Entity("DAL.Entities.InspectionZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Inspecti__3214EC07C9432B7A");

                    b.HasIndex(new[] { "Name" }, "UQ__Inspecti__737584F69C294ECF")
                        .IsUnique();

                    b.ToTable("InspectionZones");
                });

            modelBuilder.Entity("DAL.Entities.RepairComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("RepairRequestId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__RepairCo__3214EC070D1A3C05");

                    b.HasIndex("RepairRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("RepairComments");
                });

            modelBuilder.Entity("DAL.Entities.RepairRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("int");

                    b.Property<int>("BlockId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Normal");

                    b.Property<int>("RequestedById")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__RepairRe__3214EC07C27C467B");

                    b.HasIndex("BlockId");

                    b.HasIndex("RoomId");

                    b.HasIndex(new[] { "AssignedToId" }, "IX_RepairRequests_AssignedToId");

                    b.HasIndex(new[] { "RequestedById" }, "IX_RepairRequests_RequestedById");

                    b.HasIndex(new[] { "Status" }, "IX_RepairRequests_Status");

                    b.ToTable("RepairRequests", t =>
                        {
                            t.HasCheckConstraint("CK_RepairRequests_Priority", "[Priority] IN ('Low', 'Normal', 'High')");

                            t.HasCheckConstraint("CK_RepairRequests_Status", "[Status] IN ('Pending', 'InProgress', 'Completed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("DAL.Entities.Residence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateOnly>("MoveInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("MoveOutDate")
                        .HasColumnType("date");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Residenc__3214EC0775B32D31");

                    b.HasIndex("BlockId");

                    b.HasIndex(new[] { "IsCurrent" }, "IX_Residences_IsCurrent");

                    b.HasIndex(new[] { "RoomId" }, "IX_Residences_RoomId");

                    b.HasIndex(new[] { "UserId" }, "IX_Residences_UserId");

                    b.ToTable("Residences");
                });

            modelBuilder.Entity("DAL.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC0754F7CE32");

                    b.HasIndex(new[] { "Name" }, "UQ__Roles__737584F6FC860500")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DAL.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<int>("CurrentOccupancy")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__Rooms__3214EC07A1F7236C");

                    b.HasIndex("BlockId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("DAL.Entities.StudentPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("PointsType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StudentP__3214EC070FAD081C");

                    b.HasIndex(new[] { "SourceType", "SourceId" }, "IX_StudentPoints_Source");

                    b.HasIndex(new[] { "UserId" }, "IX_StudentPoints_UserId");

                    b.ToTable("StudentPoints", t =>
                        {
                            t.HasCheckConstraint("CK_StudentPoints_PointsType", "[PointsType] IN ('Award', 'Penalty')");
                        });
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07C26F86B3");

                    b.HasIndex(new[] { "RoleId" }, "IX_Users_RoleId");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E46ED61669")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534D8FB1843")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DAL.Entities.BlockWeeklyScore", b =>
                {
                    b.HasOne("DAL.Entities.Block", "Block")
                        .WithMany("BlockWeeklyScores")
                        .HasForeignKey("BlockId")
                        .IsRequired()
                        .HasConstraintName("FK__BlockWeek__Block__7E37BEF6");

                    b.Navigation("Block");
                });

            modelBuilder.Entity("DAL.Entities.Event", b =>
                {
                    b.HasOne("DAL.Entities.User", "Organizer")
                        .WithMany("Events")
                        .HasForeignKey("OrganizerId")
                        .IsRequired()
                        .HasConstraintName("FK__Events__Organize__534D60F1");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("DAL.Entities.EventParticipant", b =>
                {
                    b.HasOne("DAL.Entities.Event", "Event")
                        .WithMany("EventParticipants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__EventPart__Event__5812160E");

                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("EventParticipants")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__EventPart__UserI__59063A47");

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.Inspection", b =>
                {
                    b.HasOne("DAL.Entities.Block", "Block")
                        .WithMany("Inspections")
                        .HasForeignKey("BlockId")
                        .IsRequired()
                        .HasConstraintName("FK__Inspectio__Block__6EF57B66");

                    b.HasOne("DAL.Entities.User", "Inspector")
                        .WithMany("Inspections")
                        .HasForeignKey("InspectorId")
                        .IsRequired()
                        .HasConstraintName("FK__Inspectio__Inspe__71D1E811");

                    b.HasOne("DAL.Entities.Room", "Room")
                        .WithMany("Inspections")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK__Inspectio__RoomI__6FE99F9F");

                    b.HasOne("DAL.Entities.InspectionZone", "Zone")
                        .WithMany("Inspections")
                        .HasForeignKey("ZoneId")
                        .IsRequired()
                        .HasConstraintName("FK__Inspectio__ZoneI__70DDC3D8");

                    b.Navigation("Block");

                    b.Navigation("Inspector");

                    b.Navigation("Room");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("DAL.Entities.RepairComment", b =>
                {
                    b.HasOne("DAL.Entities.RepairRequest", "RepairRequest")
                        .WithMany("RepairComments")
                        .HasForeignKey("RepairRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__RepairCom__Repai__6754599E");

                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("RepairComments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__RepairCom__UserI__68487DD7");

                    b.Navigation("RepairRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.RepairRequest", b =>
                {
                    b.HasOne("DAL.Entities.User", "AssignedTo")
                        .WithMany("RepairRequestAssignedTos")
                        .HasForeignKey("AssignedToId")
                        .HasConstraintName("FK__RepairReq__Assig__619B8048");

                    b.HasOne("DAL.Entities.Block", "Block")
                        .WithMany("RepairRequests")
                        .HasForeignKey("BlockId")
                        .IsRequired()
                        .HasConstraintName("FK__RepairReq__Block__5EBF139D");

                    b.HasOne("DAL.Entities.User", "RequestedBy")
                        .WithMany("RepairRequestRequestedBies")
                        .HasForeignKey("RequestedById")
                        .IsRequired()
                        .HasConstraintName("FK__RepairReq__Reque__60A75C0F");

                    b.HasOne("DAL.Entities.Room", "Room")
                        .WithMany("RepairRequests")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("FK__RepairReq__RoomI__5FB337D6");

                    b.Navigation("AssignedTo");

                    b.Navigation("Block");

                    b.Navigation("RequestedBy");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DAL.Entities.Residence", b =>
                {
                    b.HasOne("DAL.Entities.Block", "Block")
                        .WithMany("Residences")
                        .HasForeignKey("BlockId")
                        .IsRequired()
                        .HasConstraintName("FK__Residence__Block__4E88ABD4");

                    b.HasOne("DAL.Entities.Room", "Room")
                        .WithMany("Residences")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK__Residence__RoomI__4D94879B");

                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("Residences")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Residence__UserI__4CA06362");

                    b.Navigation("Block");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.Room", b =>
                {
                    b.HasOne("DAL.Entities.Block", "Block")
                        .WithMany("Rooms")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Rooms__BlockId__47DBAE45");

                    b.Navigation("Block");
                });

            modelBuilder.Entity("DAL.Entities.StudentPoint", b =>
                {
                    b.HasOne("DAL.Entities.User", "User")
                        .WithMany("StudentPoints")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentPo__UserI__778AC167");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.HasOne("DAL.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__Users__RoleId__3E52440B");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DAL.Entities.Block", b =>
                {
                    b.Navigation("BlockWeeklyScores");

                    b.Navigation("Inspections");

                    b.Navigation("RepairRequests");

                    b.Navigation("Residences");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DAL.Entities.Event", b =>
                {
                    b.Navigation("EventParticipants");
                });

            modelBuilder.Entity("DAL.Entities.InspectionZone", b =>
                {
                    b.Navigation("Inspections");
                });

            modelBuilder.Entity("DAL.Entities.RepairRequest", b =>
                {
                    b.Navigation("RepairComments");
                });

            modelBuilder.Entity("DAL.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DAL.Entities.Room", b =>
                {
                    b.Navigation("Inspections");

                    b.Navigation("RepairRequests");

                    b.Navigation("Residences");
                });

            modelBuilder.Entity("DAL.Entities.User", b =>
                {
                    b.Navigation("EventParticipants");

                    b.Navigation("Events");

                    b.Navigation("Inspections");

                    b.Navigation("RepairComments");

                    b.Navigation("RepairRequestAssignedTos");

                    b.Navigation("RepairRequestRequestedBies");

                    b.Navigation("Residences");

                    b.Navigation("StudentPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
